name: Test iTunes Header Server

env:
  PYTHONIOENCODING: utf-8

on: 
  push:
  workflow_dispatch:
    inputs:
      itunes_debug_enabled:
        description: 'Run the build with iTunes ngrok-RDP debugging enabled'
        required: false
        default: false
      test_debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  repository_dispatch:

jobs:
  header_server:
    name: 'Test Setup'
    runs-on: "windows-latest"
    steps:
      - name: debug1
        run: |
            ipconfig /all
      - name: debug3
        run: |
            Get-NetIpAddress | Format-Table
      - name: Debug
        run: |
            $env:MYWINHOST=([System.Net.Dns]::GetHostByName($env:computerName).HostName)
            echo $env:MYWINHOST
            #ipconfig /all
            #tasklist
            curl -vv $($env:MYWINHOST):9000
        shell: pwsh
      - name: debug2
        run: |
            curl -vv $env:MYWINHOST:9000
      
      #- uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      #  if: ${{ always() && github.event_name == 'workflow_dispatch' && github.event.inputs.test_debug_enabled }}
      #  with:
      #    ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
      #    password: Aa123456
      #    foreground: false
